# Generated by Django 5.2.1 on 2025-06-04 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_available_exchangehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerequest',
            name='offered_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offered_requests', to='books.book', verbose_name='Libro ofertado'),
        ),
    ]
