# Generated by Django 5.2.1 on 2025-06-04 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_exchangerequest_offered_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangehistory',
            name='offered_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offered_history', to='books.book'),
        ),
        migrations.AlterField(
            model_name='exchangehistory',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_history', to='books.book'),
        ),
    ]
