# Generated by Django 5.2.1 on 2025-06-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_exchangehistory_offered_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerequest',
            name='initiated',
            field=models.BooleanField(default=False, verbose_name='Interés confirmado'),
        ),
    ]
